name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew lint

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: CuteDialog/build/reports/lint-results-debug.html


  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: CuteDialog/build/reports/tests/testDebugUnitTest

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Run Espresso Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: intrumentation-test-report
          path: CuteDialog/build/reports/androidTests/connected/

#  static-code-analysis:
#    needs: [ instrumentation-test ]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Code Checkout
#        uses: actions/checkout@v3
#
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#
#      - name: SonarClud Scan
#        run: ./gradlew app:sonarqube -Dsonar.login=${{secrets.SONAR_TOKEN}}
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    needs: [ instrumentation-test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
